config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get  'sign_up' => 'users#new'
  post 'users' => 'users#create'

  get  'sign_in' => 'sessions#login'
  get  'sessions/logout'
  post 'sessions' => 'sessions#create'

  resources :posts do
    resources :comments, only: [:new, :create]
  end

  delete 'comments/:id' => 'comments#destroy', as: 'delete_comment'
  post 'posts/:id/votes' => 'posts#votes', as: 'votes'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  after_create :update_post

  belongs_to :post
  belongs_to :user

  validates_presence_of :comment
  has_ancestry

  def update_post
    self.post.touch
  end

  def can_be_deleted?
    one_hour_ago = Time.now - 1.hour
    self.created_at >= one_hour_ago
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :voted_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :body, presence: true, length: { minimum: 140 }
  validates :title, presence: true, uniqueness: { scope: :user_id }, length: { minimum: 5, maximum: 140 }

  scope :newest, ->  { order( created_at: :desc ) }
  scope :popular, -> { order( voted_rate: :desc ) }
  scope :last_updated, -> { order( updated_at: :desc ) }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :voted_posts, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/models/voted_post.rb
class VotedPost < ActiveRecord::Base

  validates_uniqueness_of :user_id, scope: :post_id
  belongs_to :post
  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :post_owner?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    redirect_to root_path unless current_user || controller_name == 'session'
  end

  def post_owner?(post)
    current_user && post.user != current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate, only: [:new, :create, :destroy]
  before_action :get_posts, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.js
      end
    else
      redirect_to :back, notice: 'Comment cant be blank.'
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :parent_id)
  end

  def get_posts
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :votes]
  before_action :authenticate, except: [:index, :show]
  before_action :set_cookie

  # GET /posts
  def index
    @posts = if params[:popular].present?
      Post.all.popular
    elsif params[:updated].present?
      Post.all.last_updated
    else
      Post.all.newest
    end
    respond_to do |format|
      format.json { render json: @posts, except: [:updated_at, :user_id], include: { user: { only: :name } } }
      format.html
    end
  end

  # GET /posts/1
  def show
    respond_to do |format|
      format.json { render json: @post, except: [:updated_at, :user_id], include: { user: { only: :name } } }
      format.html
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def votes
    if params[:vote] === 'positive'
      @post.voted_rate += 1
    elsif params[:vote] === 'negative'
      @post.voted_rate -= 1
    end
    save_voted_post
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body, :tags)
    end

    def set_cookie
      cookies[:views] = cookies[:views].present? ? cookies[:views].to_i + 1 : 1
    end

    def save_voted_post
      voted_post = VotedPost.new(user: current_user, post: @post)
      if voted_post.valid? && @post.valid?
        voted_post.save
        @post.save
        respond_to do |format|
          format.js
        end
      else
        redirect_to :back
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def logout
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password))
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    default_url = "http://www.gravatar.com/avatar/00000000000000000000000000000000"
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=80&d=#{CGI.escape(default_url)}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_can_delete_comment?(comment)
    comment.can_be_deleted? && comment.user == current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
- comments.each do |comment|
  .next_level{ style: "padding-left: #{comment.depth*10}px;" }
    .row
      .col-md-10
        = comment.comment
      .col-md-2
        - if current_user
          = link_to 'Reply', new_post_comment_path(@post, parent_id: comment.id), remote: true, class: "add_comment#{comment.id}"
          - if user_can_delete_comment?(comment)
            %br
            =link_to 'Delete Comment', delete_comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }
    %small
      = comment.user.name
      &#124
      = comment.created_at.strftime('%d.%m.%Y')
    %div{ class: "reply#{comment.id}" }
    %hr
    = render 'comments/comment', comments: comment.children if comment.has_children?

app/views/comments/_comment_form.html.haml
= form_for [@post, @comment], remote: true do |f|
  = f.hidden_field :parent_id, value: params[:parent_id] != "0" ? params[:parent_id] : nil
  .form-group
    = f.label :comment
    = f.text_area :comment, class: 'form-control'
  = f.button submit: 'Add Comment', class: 'btn btn-default'

app/views/comments/create.js.erb
var is_root = '<%= @comment.ancestry.nil? %>';
if (is_root === 'true') {
  $('#show_new_comment_form').before('<%= j render partial: 'comment', locals: { comments: [@comment] } %>');
} else {
  var element = $('.add_comment<%= @comment.parent_id %>').parent('div').parent('div').parent('div');
  element.append('<%= j render partial: 'comment', locals: { comments: [@comment] } %>');
}
$('#new_comment').remove();

app/views/comments/new.js.erb
$('#new_comment').remove();
if ('<%= params[:parent_id] %>' == '0') {
  $('#show_new_comment_form').after('<%= j render partial: 'comment_form' %>');
} else {
  var row = $('.add_comment<%= params[:parent_id] %>').parent('div').parent('div').parent('div');
  row.find('.reply<%= params[:parent_id] %>').after('<%= j render partial: 'comment_form' %>');
}

app/views/layouts/_user_info.html.haml
.user_info
  - if current_user
    = current_user.name
    = current_user.email
    %span.v-bar
      &#124
    = link_to "Exit", sessions_logout_path
  - else
    = link_to "Sign In", sign_in_path
    %span.v-bar
      &#124
    = link_to "Register New User", sign_up_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SimpleBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #calendar
      = month_calendar table: {class: 'calendar'}, td: {class: 'day'} do |date|
        = date.day
    #wrapper.center-block
      - if cookies[:views]%10 == 0
        #banner.center-block
          %h2 Learning it is light. Do this together with GeekHub!
      #header
        %h1
          Simple
          %span Blog
        = link_to "Back To Main Page", root_path, class: 'back_to_main' unless current_page?(root_path)
        = render 'layouts/user_info'
      #content
        = yield

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      #{pluralize(@post.errors.count, "error")} prohibited this post from being saved:
      %ul
      - @post.errors.full_messages.each do |message|
        %li
          = message

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  .form-group
    = f.label :tags
    = f.text_field :tags, class: 'form-control'
  = f.button submit: "Create Post", class: "btn btn-default"

app/views/posts/_post.html.haml
#post_title
  .rates
    Rating:
    = post.voted_rate
  %h3
    %span
      = link_to post.title, post
.row
  .col-md-10
    %h4
      = post.body
    %br
    %br
    %h6
      = post.tags
  .col-md-2
    - if post.user == current_user
      %p
        = link_to edit_post_path(post) do
          = content_tag(:button, class: 'btn btn-warning') do
            Edit
      %p
        = link_to post, method: :delete, data: { confirm: 'Are you sure?' } do
          = content_tag(:button, class: 'btn btn-danger') do
            Destroy
    %p
      = image_tag avatar_url(post.user)
    %p
      Created by :
      = post.user.name
    %p
      Created at:
      = post.created_at.strftime('%d/%m/%Y')

app/views/posts/edit.html.haml
.row
  .col-md-10
    %h1 Editing post
  .col-md-2
    %h1
      = link_to root_path do
        = content_tag(:button, class: 'btn btn-info') do
          Back
= render 'form'

app/views/posts/index.html.haml
- if current_user
  .create_button
    = link_to new_post_path do
      = content_tag(:button, class: 'btn btn-primary') do
        Create
.popular
  = link_to 'Show Popular', posts_path(popular: 'true')
  %span.v-bar
    &#124
  = link_to 'Last Updated', posts_path(updated: 'true')
= render @posts

app/views/posts/new.html.haml
.row
  .col-md-10
    %h1 New post
  .col-md-2
    %h1
      = link_to root_path do
        = content_tag(:button, class: 'btn btn-info') do
          Back
= render 'form'

app/views/posts/show.html.haml
%p#notice
  = notice

.row
  .col-md-10
    .rates
      Rating:
      = link_to_if post_owner?(@post), "", votes_path(@post, vote: 'positive'), method: :post, class: 'glyphicon glyphicon-chevron-up', remote: true
      %span#voted_rate
        = @post.voted_rate
      = link_to_if post_owner?(@post), "", votes_path(@post, vote: 'negative'), method: :post, class: 'glyphicon glyphicon-chevron-down', remote: true
    %h1
      = @post.title
  .col-md-2
    %h1
      = link_to root_path do
        = content_tag(:button, class: 'btn btn-info') do
          Back
.row
  .col-md-12
    %h4
      = @post.body
    %br
    %br
    %h6
      = @post.tags
- if @post.user == current_user
  = link_to edit_post_path(@post) do
    = content_tag(:button, class: 'btn btn-warning') do
      Edit
%hr
%h4 Comments:
- @post.comments.roots.each do |c|
  = render 'comments/comment', comments: [c] if c.present?
%br
- if current_user
  = link_to new_post_comment_path(@post, parent_id: 0), remote: true, id: 'show_new_comment_form' do
    = content_tag(:button, class: 'btn btn-primary') do
      Add Comment

app/views/posts/votes.js.erb
$('#voted_rate').text('<%= @post.voted_rate %>');

app/views/users/new.html.haml
%h1 Registrations of New User
%h2 Please Fill In Registration Form
= form_for(@user) do |f|
  .form-group
    = f.label :name
    %br
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email
    %br
    = f.email_field :email, class: "form-control"
  .form-group
    = f.label :password
    %br
    = f.password_field :password, class: "form-control"
  = f.button submit: "Create User", class: "btn btn-default"